src/Entity/Zaznam.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ZaznamRepository")
 */
class Zaznam
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $osobne_cislo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $meno;

    /**
     * @ORM\Column(type="integer")
     */
    private $heslo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datum_cas_prichodu;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datum_cas_odchodu;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOsobneCislo(): ?int
    {
        return $this->osobne_cislo;
    }

    public function setOsobneCislo(int $osobne_cislo): self
    {
        $this->osobne_cislo = $osobne_cislo;

        return $this;
    }

    public function getMeno(): ?string
    {
        return $this->meno;
    }

    public function setMeno(string $meno): self
    {
        $this->meno = $meno;

        return $this;
    }

    public function getHeslo(): ?int
    {
        return $this->heslo;
    }

    public function setHeslo(int $heslo): self
    {
        $this->heslo = $heslo;

        return $this;
    }

    public function getDatumCasPrichodu(): ?\DateTime
    {
        return $this->datum_cas_prichodu;
    }

    public function setDatumCasPrichodu(\DateTime $datum_cas_prichodu): self
    {
        $this->datum_cas_prichodu = $datum_cas_prichodu;

        return $this;
    }

    public function getDatumCasOdchodu(): ?\DateTime
    {
        return $this->datum_cas_odchodu;
    }

    public function setDatumCasOdchodu(\DateTime $datum_cas_odchodu): self
    {
        $this->datum_cas_odchodu = $datum_cas_odchodu;

        return $this;
    }



}

src/Controller/DefaultController.php
<?php
namespace App\Controller;
use App\Entity\Zaznam;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request ;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController ;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response ;

class DefaultController extends AbstractController
{


    /**
     * @Route(path="/", name="index_action")
     */
    public function login (EntityManagerInterface $em) {


//        return $this->render('default/login.html.twig');

        return $this->redirectToRoute('app_login');

    }

    /**
     * @Route(path="/tabulka", name="tabulka_action")
     */
    public function tabulka (EntityManagerInterface $em ) {

        /** @var Zaznam[] $zaznam */
          $zaznam= $em -> getRepository(Zaznam::class)->findAll();
//        $zaznam = $this->getDoctrine()->getRepository('Zaznam')->findAll();

        return $this->render('default/tabulka.html.twig',[
            'zaznam' => $zaznam
        ]);

    }


}

templates/default/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Treningovy projekt{% endblock %}

{% block body %}


<style>
    #subscribe,
    #login{


        position: absolute;
        top: 0px;
        width: 87%;
        padding: 18px 6% 60px 6%;
        margin: 0 0 35px 0;
        background: rgb(247, 247, 247);
        border: 1px solid rgba(147, 184, 189,0.8);
        box-shadow:
                0pt 2px 5px rgba(105, 108, 109,  0.7),
                0px 0px 8px 5px rgba(208, 223, 226, 0.4) inset;
        border-radius: 5px;
    }
    #login{
        z-index: 22;
    }
    .animate form2 {
        margin: 0rem!important;
        padding: 4rem!important;
        /*margin-left: 24.3rem;*/
        /*margin-top: 2rem;*/

        margin-left: 9rem!important;
        margin-top: 8rem!important;

    }
</style>


<div id="wrapper">
    <div id="login" class="animate form2" style="margin-left: 7rem; margin-top:3rem ;">
        <form  action="mysuperscript.php" style="margin-left: 40rem;" autocomplete="on">
            <h1 style="margin-left: 2rem;">Prihlásiť sa</h1>
            <p>
                <label for="username" class="uname" data-icon="u" > Meno </label>
                <input  id="username" name="username" required="required" type="text"/>
            </p>
            <p>
                <label for="password" class="youpasswd" data-icon="p"> Heslo </label>
                <input id="password" name="password" required="required" type="password" />
            </p>
            <p class="keeplogin">
                <input style="margin-left: 3rem;" type="checkbox" name="loginkeeping" id="loginkeeping" value="loginkeeping" />
                <label for="loginkeeping">Ostat prihlaseny</label>
            </p>
            <p class="login button">
                <input type="submit" style="margin-left: 4rem;" value="Prihlásiť sa" />
            </p>
        </form>
    </div>


    </div>

</div>
</div>

{% endblock %}

templates/default/tabulka.html.twig
{% extends 'base.html.twig' %}

{% block title %}Treningovy projekt{% endblock %}

{% block body %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style type="text/css">
        .tg  {border-collapse:collapse;border-spacing:0;border-color:#999;}
        .tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:0px;overflow:hidden;word-break:normal;border-color:#999;color:#444;background-color:#F7FDFA;}
        .tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:0px;overflow:hidden;word-break:normal;border-color:#999;color:#fff;background-color:#26ADE4;}
        .tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
        .tg .tg-0lax{text-align:left;vertical-align:top}
    </style>

    <table class="tg" style="margin-left: 12rem;
margin-top: 6rem;">
        <colgroup>
            <col style="width: 237px">
            <col style="width: 304px">
            <col style="width: 318px">
            <col style="width: 204px">
        </colgroup>
        {% if is_granted('ROLE_ADMIN') %}
            <div class="col">
                <button onclick="location.href = 'http://localhost:8000/tabulka/new';" id="myButton" class="btn btn-success float-right" >Pridaj novy zaznam</button>
            </div>

        {% endif %}
        <tr>
            <th class="tg-0pky">Osobne číslo<br></th>
            <th class="tg-0lax">Meno</th>
            <th class="tg-0lax">Datum a čas príchodu</th>
            <th class="tg-0lax">Datum a čas odchodu</th>
           {% if is_granted('ROLE_ADMIN') %}
            <th class="tg-0lax">Edit</th>
            <th class="tg-0lax">Delete</th>
            {% endif %}
        </tr>
        {% for zaznamy in zaznam %}
        <tr>
            <td  class="tg-0lax">
                {{ zaznamy.osobneCislo }}
                <br></td>
            <td class="tg-0lax">
                    {{ zaznamy.meno }}
                <br></td>
            <td class="tg-0lax">
                    {{ zaznamy.datumCasOdchodu | date('d/m/Y') }}
                <br></td>
            <td class="tg-0lax">
                    {{ zaznamy.datumCasPrichodu | date('d/m/Y') }}
            </td>
            {% if is_granted('ROLE_ADMIN') %}
            <td class="tg-0lax">
                <a class="fa fa-edit" style="font-size:24px" href="http://localhost:8000/tabulka/zaznam/{{ zaznamy.id }}/edit"> </a>
            </td>
            <td class="tg-0lax">
                <a class="fa fa-edit" style="font-size:24px" href="http://localhost:8000/tabulka/zaznam/{{ zaznamy.id }}/delete"> </a>
            </td>
            {% endif %}
        </tr>

        {% endfor %}
    </table>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('/js/admin.js') }}"></script>
{% endblock %}